server:
  port: 8080
  address: 0.0.0.0

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

spring:
  application:
    name: audioTranscriberAi

  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-2.5-flash-lite

    elevenlabs:
      api-key: ${ELEVENLABS_API_KEY}
      base-url: "https://api.elevenlabs.io/v1"
      tts:
        options:
          model: scribe_v1

    groq:
      api-key: ${GROQ_API_KEY}
      base-url: "https://api.groq.com/openai/v1"
      options:
        model: whisper-large-v3-turbo

    assemblyai:
      api-key: ${ASSEMBLY_API_KEY}
      base-url: "https://api.assemblyai.com/v2"
